# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repertoire', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(null=True),
        ),
    ]
