# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repertoire', '0003_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audioFile',
            field=models.FileField(null=True, upload_to='audioRepository'),
        ),
    ]
