# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repertoire', '0004_song_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to='audioRepository'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
