# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
