# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Performances', '0001_initial'),
    ]

    operations = [
    ]
