# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performances', '0003_auto_20160918_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songorder',
            name='orderInPerformance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
