# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performances', '0004_auto_20160918_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
