# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performances', '0004_auto_20160916_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songorder',
            name='orderInPerformance',
            field=models.IntegerField(),
        ),
    ]
